version: '3.8'

services:
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./app:/symfony
    container_name: ${PROJECT_NAME}-nginx
    restart: always
    ports:
      - "8081:80"
    links:
      - php-fpm

  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
      - ./app:/symfony
      - ./docker/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    environment:
      XDEBUG_SESSION: PHPSTORM
      PHP_IDE_CONFIG: "serverName=Tenders"
    restart: always
    container_name: ${PROJECT_NAME}-php
    extra_hosts:
      - "host.docker.internal:$DOCKER_INTERNAL_IP"
      - "api.local:$DOCKER_INTERNAL_IP"

  mysql:
    image: mysql:8.0
    command: --mysql-native-password=ON
    volumes:
      - ./docker/mysql:/var/lib/mysql
    container_name: ${PROJECT_NAME}-mysql
    restart: always
    ports:
      - "3309:3309"
    environment:
      MYSQL_ROOT_PASSWORD: 62876087
      MYSQL_DATABASE: tenders
      MYSQL_USER: user
      MYSQL_PASSWORD: password